name: Update chains config

on:
  workflow_dispatch:

jobs:
  cron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 20 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout 📡
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache node_modules 💰
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies 🧬
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Update chains
        run: npm run update
        env:
          CI: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
